title: Tabletop Club
tagline: The free and open source board game simulator
description: Play tabletop games in a physics-based, 3D environment with your friends, no logins or sign-ups required.
url: https://tabletopclub.net
logo: /assets/images/tabletop_club_icon.png
locale: en_GB

social:
  name: Benjamin Beddows
  links:
    - https://github.com/drwhut
    - https://ko-fi.com/drwhut

exclude:
  [
    "build.sh",
    "downloads/releases/build.sh",
    "CONTRIBUTING.md",
    "LICENSE",
    "README.md",
    "SECURITY.md",
  ]

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
