name: Test Site
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: actions/jekyll-build-pages@v1
